### ISSUE TITLE
Integrating pyrealsense2 codes abour T265

### ISSUE THREAD

**Issue by Suke0811** [Suke0811/Localization_T265#1]
## Making this library stand alone
Since intel has dropped support and codes for t265 from their pyrealsense2 library starting [Ver. 2.54.1](https://github.com/IntelRealSense/librealsense/releases/tag/v2.54.1), now maybe we should include all necessary codes for operating T265 in this library. 

Then, we can install the latest and future versions, and still use t265. 
Since they removed the codes entirely, implanting them should be okay (check licenses)

## Tasks

* [ ] Identify codes necessary to run T265 from Ver. 2.53.1
* [ ] Sort and organize the codes for easier handling (No plan to support any other cameras at all)
* [ ] Adding Mkdocs on this lib
* [ ] Check licenses on pyrealsense to see the conditions for reusing their codes. 
* [ ] Bump the version to Ver. 0.2.xx

**Comment by Suke0811** [comment]
This seems to be annoying to do since the code is pybinded so it requires deep digging. It may be easier to just try pyserial if we only support t265
